### ISSUE TITLE
“A JavaScript error occurred in the main process”

### ISSUE THREAD

**Issue by SWJSalmon** [mkinfrared/baldurs-gate3-mod-manager#132]
Hi, I have been using mod manager for a few weeks now and it was working great for me, until today when this message that I will put below keeps popping up when I open up mod manager. Tried deleting and reinstalling the mod manager, didn't work.
This message blocks me from doing anything with mod manager and basically freezes the mod manager window, I had to force quit mod manager to close the mod manager app.
Is there any solution to this? I would really appreciate any help, thanks.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Invalid incoming JSON: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.Stream.ReadAtLeastCore(Span`1, Int32, Boolean)
at System.IO.Stream.ReadExactly(Span`1)
at System.IO.BinaryReader.InternalRead(Int32)
at System.IO.BinaryReader.ReadInt32()
at PakReader.PackageReader.ReadFileListV18(BinaryReader, Package)
at PakReader.PackageReader.ReadPackageV18(FileStream, BinaryReader)
at PakReader.PackageReader.Read()
at Program.<>c.<Main>b__0_0(String )
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.Stream.ReadAtLeastCore(Span`1, Int32, Boolean)
at System.IO.Stream.ReadExactly(Span`1)
at System.IO.BinaryReader.InternalRead(Int32)
at System.IO.BinaryReader.ReadInt32()
at PakReader.PackageReader.ReadFileListV18(BinaryReader, Package)
at PakReader.PackageReader.ReadPackageV18(FileStream, BinaryReader)
at PakReader.PackageReader.Read()
at Program.<>c.<Main>b__0_0(String )
{"type":"RESPONSE","response":{"result":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxzYXZlPg0KICAgIDx2ZXJzaW9uIG1ham9yPSI0IiBtaW5vcj0iMCIgcmV2aXNpb249IjkiIGJ1aWxkPSIzMzEiLz4NCiAgICA8cmVnaW9uIGlkPSJDb25maWciPg0KICAgICAgICA8bm9kZSBpZD0icm9vdCI+DQogICAgICAgICAgICA8Y2hpbGRyZW4+DQogICAgICAgICAgICAgICAgPG5vZGUgaWQ9IkRlcGVuZGVuY2llcyIvPg0KICAgICAgICAgICAgICAgIDxub2RlIGlkPSJNb2R1bGVJbmZvIj4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iQXV0aG9yIiB0eXBlPSJMU1N0cmluZyIgdmFsdWU9IkxpYXJldGgiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iQ2hhcmFjdGVyQ3JlYXRpb25MZXZlbE5hbWUiIHR5cGU9IkZpeGVkU3RyaW5nIiB2YWx1ZT0iIi8+DQogICAgICAgICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IkRlc2NyaXB0aW9uIiB0eXBlPSJMU1N0cmluZyIgdmFsdWU9IkFkZHMgdmFyaW91cyBuZXcgYmFncyBmb3Igc2FsZSIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJGb2xkZXIiIHR5cGU9IkxTU3RyaW5nIiB2YWx1ZT0iQmFnc0JhZ3NCYWdzIi8+DQogICAgICAgICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IkxvYmJ5TGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJNRDUiIHR5cGU9IkxTU3RyaW5nIiB2YWx1ZT0iIi8+DQogICAgICAgICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9Ik1haW5NZW51QmFja2dyb3VuZFZpZGVvIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJNZW51TGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IkJhZ3NCYWdzQmFncyIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJOdW1QbGF5ZXJzIiB0eXBlPSJ1aW50OCIgdmFsdWU9IjQiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iUGhvdG9Cb290aCIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iU3RhcnR1cExldmVsTmFtZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVGFncyIgdHlwZT0iTFNTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVHlwZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJBZGQtb24iLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVVVJRCIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIzZTE1OGZiOC02ODZlLTQxNTMtOTQzMC1lMjdmNGI5ZmI3ZjgiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVmVyc2lvbiIgdHlwZT0iaW50NjQiIHZhbHVlPSIxNDQxMTUxODgwNzU4NTU5MTIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGNoaWxkcmVuPg0KICAgICAgICAgICAgICAgICAgICAgICAgPG5vZGUgaWQ9IlB1Ymxpc2hWZXJzaW9uIj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJWZXJzaW9uIiB0eXBlPSJpbnQ2NCIgdmFsdWU9IjE0NDExNTE4ODA3NTg1NTkxMiIvPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC9ub2RlPg0KICAgICAgICAgICAgICAgICAgICAgICAgPG5vZGUgaWQ9IlNjcmlwdHMiLz4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxub2RlIGlkPSJUYXJnZXRNb2RlcyI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNoaWxkcmVuPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bm9kZSBpZD0iVGFyZ2V0Ij4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9Ik9iamVjdCIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJTdG9yeSIvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L25vZGU+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9jaGlsZHJlbj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICAgICAgICAgICAgPC9jaGlsZHJlbj4NCiAgICAgICAgICAgICAgICA8L25vZGU+DQogICAgICAgICAgICA8L2NoaWxkcmVuPg0KICAgICAgICA8L25vZGU+DQogICAgPC9yZWdpb24+DQo8L3NhdmU+DQo=","id":"1e068d65-7002-4e23-b048-72fc0c332d9f"}}
at TabSeparatedInputStreamParser.addPartial (/Applications/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/tab-separated-input-stream-parser.js:16:23)
at Socket.<anonymous> (/Applications/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/connection.js:13:27)
at Socket.emit (node:events:514:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:293:11)
at Socket.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

- Manager Version : v1.5.0
- Link to problem mod : don't know how to do this
- Operating System and version : macOS Sonoma 14.1.1 (23B81)

**Comment by SWJSalmon** [comment]
nvm I fixed the problem. 
just in case anyone encountered the same problem as mine, here's how I fixed it:
so there was a problem with the "Mods" folder that is in the Baldur's Gate 3 folder, so I just deleted the Mods folder and restarted the game than reinstalled the mod manager and all the mods and everything was fine.
