### ISSUE TITLE
JavaScript error occured in the main process

### ISSUE THREAD

**Issue by RobbCorrea** [mkinfrared/baldurs-gate3-mod-manager#177]
## Your Environment

Hello, it's totally jammed. Idk, how it happened. It used to run properly. Now all it shows is this:

Uncaught Exception:
Error: Invalid incoming JSON: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.Stream.ReadAtLeastCore(Span`1, Int32, Boolean)
at System.IO.Stream.ReadExactly(Span`1)
at System.IO.BinaryReader.InternalRead(Int32)
at System.IO.BinaryReader.ReadInt32()
at PakReader.PackageReader.ReadFileListV18(BinaryReader, Package)
at PakReader.PackageReader.ReadPackageV18(FileStream, BinaryReader)
at PakReader.PackageReader.Read()
at Program.<>c.<Main>b__0_0(String )
{"type":"RESPONSE","response":{"result":"77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjxzYXZlPg0KICA8dmVyc2lvbiBtYWpvcj0iNCIgbWlub3I9IjAiIHJldmlzaW9uPSI3IiBidWlsZD0iMiIgLz4NCiAgPHJlZ2lvbiBpZD0iQ29uZmlnIj4NCiAgICA8bm9kZSBpZD0icm9vdCI+DQogICAgICA8Y2hpbGRyZW4+DQogICAgICAgIDxub2RlIGlkPSJEZXBlbmRlbmNpZXMiIC8+DQogICAgICAgIDxub2RlIGlkPSJNb2R1bGVJbmZvIj4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJBdXRob3IiIHR5cGU9IkxTV1N0cmluZyIgdmFsdWU9IktoYXJuZXRoIiAvPg0KICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IkNoYXJhY3RlckNyZWF0aW9uTGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJEZXNjcmlwdGlvbiIgdHlwZT0iTFNXU3RyaW5nIiB2YWx1ZT0iTmV3IEd1bmJsYWRlIHdlYXBvbiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJGb2xkZXIiIHR5cGU9IkxTV1N0cmluZyIgdmFsdWU9IkZGX0d1bmJsYWRlIiAvPg0KICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IkdNVGVtcGxhdGUiIHR5cGU9IkZpeGVkU3RyaW5nIiB2YWx1ZT0iIiAvPg0KICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IkxvYmJ5TGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJNRDUiIHR5cGU9IkxTU3RyaW5nIiB2YWx1ZT0iIiAvPg0KICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9Ik1haW5NZW51QmFja2dyb3VuZFZpZGVvIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJNZW51TGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IkZGX0d1bmJsYWRlIiAvPg0KICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9Ik51bVBsYXllcnMiIHR5cGU9InVpbnQ4IiB2YWx1ZT0iNCIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJQaG90b0Jvb3RoIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJTdGFydHVwTGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIgLz4NCiAgICAgICAgICA8YXR0cmlidXRlIGlkPSJUYWdzIiB0eXBlPSJMU1dTdHJpbmciIHZhbHVlPSIiIC8+DQogICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVHlwZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJBZGQtb24iIC8+DQogICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVVVJRCIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSI1ZDI1MmU3NS0yMWRlLTQwODktYjExZC04MzM5NzI1N2VjZGYiIC8+DQogICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVmVyc2lvbjY0IiB0eXBlPSJpbnQ2NCIgdmFsdWU9IjM2MDI4Nzk3MDE4OTYzOTY4IiAvPg0KICAgICAgICAgIDxjaGlsZHJlbj4NCiAgICAgICAgICAgIDxub2RlIGlkPSJQdWJsaXNoVmVyc2lvbiI+DQogICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9IlZlcnNpb242NCIgdHlwZT0iaW50NjQiIHZhbHVlPSIzNjAyODc5NzAxODk2Mzk2OCIgLz4NCiAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICAgIDxub2RlIGlkPSJTY3JpcHRzIiAvPg0KICAgICAgICAgICAgPG5vZGUgaWQ9IlRhcmdldE1vZGVzIj4NCiAgICAgICAgICAgICAgPGNoaWxkcmVuPg0KICAgICAgICAgICAgICAgIDxub2RlIGlkPSJUYXJnZXQiPg0KICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iT2JqZWN0IiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IlN0b3J5IiAvPg0KICAgICAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICAgICAgPC9jaGlsZHJlbj4NCiAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICA8L2NoaWxkcmVuPg0KICAgICAgICA8L25vZGU+DQogICAgICA8L2NoaWxkcmVuPg0KICAgIDwvbm9kZT4NCiAgPC9yZWdpb24+DQo8L3NhdmU+","id":"dc467974-6500-4c51-9d89-8ff99909be7c"}}
at TabSeparatedInputStreamParser.addPartial (/Applications/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/tab-separated-input-stream-parser.js:16:23)
at Socket.<anonymous> (/Applications/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/connection.js:13:27)
at Socket.emit (node:events:514:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:293:11)
at Socket.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

And even if I uninstall it, it will appear over and over again.

What can I do?

Thank you for your help. :)

- Manager Version :
- Link to problem mod :
- Operating System and version :

**Comment by undersnails** [comment]
did you ever find a fix for it? i'm having the same issue
